miders = [
    {'hero': 'Shadow Fiend', 'media': ''},
    {'hero': 'Storm Spirit', 'media': ''},
    {'hero': 'Tinker', 'media': ''},
    {'hero': 'Templar Assassin', 'media': ''},
    {'hero': 'Invoker', 'media': ''},
    {'hero': 'Outworld Destroyer', 'media': ''},
    {'hero': 'Void Spirit', 'media': ''},
    {'hero': 'Queen of Pain', 'media': ''},
    {'hero': 'Ember Spirit', 'media': ''},
    {'hero': 'Puck', 'media': ''},
    {'hero': 'Death Prophet', 'media': ''},
    {'hero': 'Zeus', 'media': ''},
    {'hero': 'Meepo', 'media': ''},
    {'hero': 'Arc Warden', 'media': ''},
    {'hero': 'Sniper', 'media': ''},
    {'hero': 'Viper', 'media': ''},
    {'hero': 'Alchemist', 'media': ''},
    {'hero': 'Lina', 'media': ''},
    {'hero': 'Huskar', 'media': ''},
    {'hero': 'Kunkka', 'media': ''},
    {'hero': 'Leshrac', 'media': ''},
    {'hero': 'Broodmother', 'media': ''},
    {'hero': 'Visage', 'media': ''},
    {'hero': 'Razor', 'media': ''},
    {'hero': 'Clinkz', 'media': ''},
    {'hero': 'Dragon Knight', 'media': ''},
    {'hero': 'Windranger', 'media': ''},
    {'hero': 'Medusa', 'media': ''},
    {'hero': 'Pugna', 'media': ''},
    {'hero': 'Monkey King', 'media': ''},
    {'hero': 'Necrophos', 'media': ''},
    {'hero': 'Morphling', 'media': ''},
    {'hero': 'Magnus', 'media': ''},
    {'hero': 'Tiny', 'media': ''},
    {'hero': 'Skywrath Mage', 'media': ''},
    {'hero': 'Lone Druid', 'media': ''},
    {'hero': 'Mirana', 'media': ''},
    {'hero': 'Pudge', 'media': ''},
    {'hero': 'Batrider', 'media': ''},
    {'hero': 'Silencer', 'media': ''},
]