miders = [
    {'hero': 'Shadow Fiend', 'media': 'pic/sf.jpg'},
    {'hero': 'Storm Spirit', 'media': 'pic/sspirit.jpg'},
    {'hero': 'Tinker', 'media': 'pic/tinker.jpg'},
    {'hero': 'Templar Assassin', 'media': 'https://thumbs.gfycat.com/ScalyHotArcticwolf-mobile.mp4'},
    {'hero': 'Invoker', 'media': 'pic/invo.jpg'},
    {'hero': 'Outworld Destroyer', 'media': 'https://64.media.tumblr.com/6be9c4532b7d589b2531a707d1166407/tumblr_nb4ryvzltT1tdis3to1_400.gifv'},
    {'hero': 'Void Spirit', 'media': 'https://c.tenor.com/IN5BSd_7mdMAAAAC/void-spirit-dota2.gif'},
    {'hero': 'Queen of Pain', 'media': 'https://i.gifer.com/B4eK.mp4'},
    {'hero': 'Ember Spirit', 'media': 'http://img2.reactor.cc/pics/post/Dota-%D1%84%D1%8D%D0%BD%D0%B4%D0%BE%D0%BC%D1%8B-Xin-the-Ember-Spirit-rogalio-2509330.gif'},
    {'hero': 'Puck', 'media': 'http://img2.reactor.cc/pics/post/Puck-Dota-%D1%84%D1%8D%D0%BD%D0%B4%D0%BE%D0%BC%D1%8B-Dota-2-1113194.gif'},
    {'hero': 'Death Prophet', 'media': 'https://phoneky.co.uk/thumbs/screensavers/down/games/dota-death_kpbl43t1.gif'},
    {'hero': 'Zeus', 'media': 'https://img1.picmix.com/output/pic/normal/3/8/4/8/6958483_1017b.gif'},
    {'hero': 'Meepo', 'media': 'https://thumbs.gfycat.com/CooperativeElementaryDodo-size_restricted.gif'},
    {'hero': 'Arc Warden', 'media': 'pic/arcwarden.gif'},
    {'hero': 'Sniper', 'media': 'https://c.tenor.com/m7Su6zWuGagAAAAC/anime-sniper.gif'},
    {'hero': 'Viper', 'media': 'http://1.bp.blogspot.com/-3yUbbCgJviU/U0VPdmA-K6I/AAAAAAAAACA/wcZYCmCHyco/s1600/3665524_5.gif'},
    {'hero': 'Alchemist', 'media': 'http://img2.reactor.cc/pics/post/Alchemist-%28Dota%29-Dota-%D1%84%D1%8D%D0%BD%D0%B4%D0%BE%D0%BC%D1%8B-Abaddon-%28Dota%29-1412737.gif'},
    {'hero': 'Lina', 'media': 'pic/lina.jpg'},
    {'hero': 'Huskar', 'media': 'pic/huskar.jpeg'},
    {'hero': 'Kunkka', 'media': 'https://i.makeagif.com/media/1-02-2016/9s3-oE.mp4'},
    {'hero': 'Leshrac', 'media': 'https://i.makeagif.com/media/5-18-2016/hhKEGc.mp4'},
    {'hero': 'Broodmother', 'media': 'https://thumbs.gfycat.com/InsignificantCalmCattle-mobile.mp4'},
    {'hero': 'Visage', 'media': 'https://i.imgur.com/afIEU9W.gif'},
    {'hero': 'Razor', 'media': 'https://i.giphy.com/media/vNqgL8Rv3Qta5rFB9s/giphy.webp'},
    {'hero': 'Clinkz', 'media': 'https://c.tenor.com/_2DJyvJaEHQAAAAC/sans-undertale.gif'},
    {'hero': 'Dragon Knight', 'media': 'https://c.tenor.com/3w42k9boBT8AAAPo/kamen-rider-dragon-knight.mp4'},
    {'hero': 'Windranger', 'media': 'http://img2.reactor.cc/pics/post/Agito666-artist-Windranger-Dota-2831130.gif'},
    {'hero': 'Medusa', 'media': 'pic/8MoH.mp4'},
    {'hero': 'Pugna', 'media': 'https://thumbs.gfycat.com/RegalAdorableCommabutterfly-mobile.mp4'},
    {'hero': 'Monkey King', 'media': 'pic/mk.jpg'},
    {'hero': 'Necrophos', 'media': 'http://img2.joyreactor.cc/pics/post/my-little-pony-%D1%84%D1%8D%D0%BD%D0%B4%D0%BE%D0%BC%D1%8B-mlp-gif-mlp-OC-900734.gif'},
    {'hero': 'Morphling', 'media': 'http://www.gamenmeme.com/wp-content/uploads/2016/07/6bf7f356fb5f20d0e88d30784c0630d9.gif'},
    {'hero': 'Magnus', 'media': 'pic/magnus.jpg'},
    {'hero': 'Tiny', 'media': 'http://img2.reactor.cc/pics/post/Dota-%D1%84%D1%8D%D0%BD%D0%B4%D0%BE%D0%BC%D1%8B-Dota-Gif-Pixel-Gif-1459661.gif'},
    {'hero': 'Skywrath Mage', 'media': 'https://i.gifer.com/IVsj.mp4'},
    {'hero': 'Lone Druid', 'media': 'pic/lonedruid.jpg'},
    {'hero': 'Mirana', 'media': 'https://thumbs.gfycat.com/LargeBackElkhound-max-1mb.gif'},
    {'hero': 'Pudge', 'media': 'pic/pudge.jpg'},
    {'hero': 'Batrider', 'media': 'https://c.tenor.com/qR9DOBr6eaYAAAAM/batman-funny.gif'},
    {'hero': 'Silencer', 'media': 'https://i.makeagif.com/media/10-10-2015/_pFajN.mp4'},
]